### ISSUE TITLE
Patient: gender.extension

### ISSUE THREAD

**Issue by helmavdl** [vzvznl/Koppeltaal-2.0-FHIR#16]
Waarom hebben we ineens een Nictiz codelijst. Is dat de bedoeling?
url: http://nictiz.nl/fhir/StructureDefinition/ext-CodeSpecification

**Comment by helmavdl** [comment]
Dat is zo bedoeld. Het KT2_Patient profiel is gebaseerd op het standaard Nictiz nl-core-Patient profiel. Die heeft er voor gekozen om een eigen, op SNOMED gebaseerde geslachtCodelijst te hanteren (die hergebruikt wordt in allerlei profielen en HL7v3 templates). Omdat de standaard FHIR Patient Resource een verplichte binding heeft met een eigen codelijst, is het noodzakelijk om een extension te maken op het gender element om een andere codelijst te kunnen gebruiken.

**Comment by wijngaard01** [comment]
Oke.
