### ISSUE TITLE
Practitioner: gender.extension

### ISSUE THREAD

**Issue by helmavdl** [vzvznl/Koppeltaal-2.0-FHIR#17]
Waarom hebben we ineens een Nictiz codelijst. Is dat de bedoeling?
url: http://nictiz.nl/fhir/StructureDefinition/ext-CodeSpecification

**Comment by helmavdl** [comment]
Dat is zo bedoeld. Het KT2_Practitioner profiel is gebaseerd op het standaard Nictiz nl-core-HealthProfessional-Practitioner profiel. Die heeft er voor gekozen om een eigen, op SNOMED gebaseerde geslachtCodelijst te hanteren (die hergebruikt wordt in allerlei profielen en HL7v3 templates). Omdat de standaard FHIR Patient Resource een verplichte binding heeft met een eigen codelijst, is het noodzakelijk om een extension te maken op het gender element om een andere codelijst te kunnen gebruiken.

**Comment by hepabolu** [comment]
Bijgaand plaatje toont hoe je er bij komt voor de Patient, maar voor de Practitioner geldt hetzelfde. 

![CleanShot 2022-12-19-12-40@2x](https://user-images.githubusercontent.com/7474858/208418345-de6b598b-4bee-4844-a8c9-f89d507495d0.png)

Als je op de link klikt kom je hier uit: https://simplifier.net/packages/nictiz.fhir.nl.r4.zib2020/0.6.0-beta.2/files/691097

De ValueSet bestaat dus uit 4 codes uit 2 verschillende CodeSystems.

**Comment by wijngaard01** [comment]
Gevonden. Oke.
