### ISSUE TITLE
Task: extension.observer

### ISSUE THREAD

**Issue by helmavdl** [vzvznl/Koppeltaal-2.0-FHIR#18]
Hiervan hebben we lang geleden al gezegd dat deze verwijderd kan worden. Reference naar CareTeam kan in het element 'owner' gezet worden.

**Comment by helmavdl** [comment]
Ik kan deze uitspraak nergens terugvinden, maar ik ga er vanuit dat deze klopt. Ik heb daarom deze extension verwijderd.

**Comment by helmavdl** [comment]
NB bij 'owner' kan maar 1 eigenaar toegevoegd worden, dus in het voorbeeld Task.json, is de patiënt de owner, en dus kan het CareTeam niet meer toegevoegd worden.

**Comment by helmavdl** [comment]
Besproken met Marcel Schrauwen. Mijn opmerking in het vorige comment is weliswaar correct, maar de relatie met het CareTeam van de patiënt wordt op een andere manier gemaakt.

**Comment by wijngaard01** [comment]
Oke.
