### ISSUE TITLE
CareTeam baseren op nl-core-CareTeam

### ISSUE THREAD

**Issue by helmavdl** [vzvznl/Koppeltaal-2.0-FHIR#19]
Het profiel blijkt nog niet op nl-core-CareTeam gebaseerd te zijn

**Comment by helmavdl** [comment]
Profiel is gebaseerd op nl-core-CareTeam. Daarbij is een extra slice gemaakt op participant omdat het anders niet mogelijk is om practitioner die conformeert aan het KT2_Practitioner profiel toe te voegen als member. Daarbij is de ValueSet binding van de rol wel overgenomen uit de oorspronkelijke slice (healthcareProfessional).

Reden voor extra slice: participant:healthcareProfessional.member verwacht een nl-core-HealthProfessional-PractitionerRole die weer refereert aan een nl-core-HealthProfessional-Practitioner. Dit zou betekenen dat ik een KT profiel voor nl-core-HealthProfessional-PractitionerRole moet maken die weer naar KT2_Practitioner verwijst. Daarbij zou ik dan alsnog de originele slice moeten aanpassen. Om het zuiver te houden, zodat later omschakelen eenvoudiger wordt, heb ik de originele slice gelaten voor wat het is, met een comment om hem niet te gebruiken, en een nieuwe slice toegevoegd die alleen voor Koppeltaal 2.0 bedoeld is.

NB. de slices onderscheiden zich op het member element. Hoewel dit optioneel is, MOET het wel aanwezig zijn in een participant object, anders volgt een validatie-fout.

**Comment by helmavdl** [comment]
Tracking Bits issue met bevinding: https://bits.nictiz.nl/browse/MM-4143

**Comment by wijngaard01** [comment]
Oke. 
Nog wel een vraag: bij CareTeam.participant.contactperson wordt referentie naar nl core contactperson gezet. Die kennen we niet bij KT. We gaan nog wel in de toekomst een RelatedPerson toevoegen. Moeten we hier nog iets mee?

**Comment by helmavdl** [comment]
Zoals besproken tijdens overleg van 2023-01-17: contactperson is een refentie naar nl-core-contactperson die op zijn beurt op RelatedPerson is gebaseerd.

In het commentaar is opgenomen dat dit element niet gebruikt wordt.
