### ISSUE TITLE
ActivityDefinition: subject

### ISSUE THREAD

**Issue by helmavdl** [vzvznl/Koppeltaal-2.0-FHIR#4]
subject
subject.subjectCodeableConcept
subject.subjectReference

Nieuw element binnen ActivityDefinition. Waar is deze voor bedoeld? En waarom ontbreekt elke informatie bij de beide subelementen?

**Comment by helmavdl** [comment]
subject is een standaard element van de HL7 Resource ActivityDefinition. Met wat goede wil zou ik dat vertalen als 'onderwerp'. Dat element is volgens het overzicht in https://confluence.vzvz.nl/display/KTDOC/TOP-KT-009+-+Overzicht+gebruikte+FHIR+Resources optioneel, dus dat kan genegeerd worden.

**Comment by wijngaard01** [comment]
Simplifier bevat geen informatie. Als we het voor Koppeltaal niet willen gebruiken, dan zou het verwijderd moeten worden. Is het bedoeld voor optioneel gebruik dan zou Simplifier ook informatie over het element moeten bevatten.

**Comment by helmavdl** [comment]
Het ziet er naar uit dat 'subject' geen vrije tekst 'onderwerp' weergeeft, maar een verwijzing naar het soort object waar de ActivityDefinition voor bedoeld is. Ik heb het element weggehaald.

**Comment by wijngaard01** [comment]
Oke.
