### ISSUE TITLE
CareTeam

### ISSUE THREAD

**Issue by helmavdl** [vzvznl/Koppeltaal-2.0-FHIR#7]
participant.member 

Kan een referentie bevatten naar Practitioner en CareTeam. Klopt dat? Snap CareTeam hier niet.

**Comment by helmavdl** [comment]
Ik kan de verwijzing naar een CareTeam niet terugvinden en omdat het element 'participant' optioneel is, heb ik de referentie naar een CareTeam profiel verwijderd.

**Comment by helmavdl** [comment]
Met Marcel Schrauwen besproken: het is niet logisch dat een CareTeam weer onderdeel is van een ander CareTeam. Voor nu is de aanpassing correct.

**Comment by wijngaard01** [comment]
Oke.
