### ISSUE TITLE
Device versie

### ISSUE THREAD

**Issue by helmavdl** [vzvznl/Koppeltaal-2.0-FHIR#8]
Versie profiel in Simplifier is van 15-7-2022. Het bevat elementen die niet voor KT bedoeld zijn. Het profiel moet nog aangepast worden.

**Comment by helmavdl** [comment]
Waar vind ik de beschrijving van wat er wel in moet zitten?

**Comment by helmavdl** [comment]
Overleg met Marcel Schrauwen: alle niet-zorggerelateerde profielen (zoals Device) hoeven geen restricties te hebben op de elementen, m.a.w. alles dat niet verplicht is, is optioneel en mag gewoon in de uitwisseling voorkomen.

**Comment by wijngaard01** [comment]
Afspraak was dat de profielen de elementen voor KT zouden bevatten. Elementen die niet voor KT gebruikt worden zouden verwijderd worden. Dit levert ruis op en miscommunicatie.
