### ISSUE TITLE
Endpoint versie

### ISSUE THREAD

**Issue by helmavdl** [vzvznl/Koppeltaal-2.0-FHIR#9]
Versie profiel in Simplifier is van 15-7-2022. Het bevat elementen die niet voor KT bedoeld zijn. Het profiel moet nog aangepast worden.

**Comment by helmavdl** [comment]
Waar vind ik de beschrijving wat er wel in hoort te zitten?

**Comment by helmavdl** [comment]
Zoals besproken met Marcel: het is een technische entititeit. Het is geen probleem dat er elementen in zitten die binnen Koppeltaal niet nodig zijn/gebruikt worden.

**Comment by wijngaard01** [comment]
Afspraak was dat de profielen de elementen voor KT zouden bevatten. Elementen die niet voor KT gebruikt worden zouden verwijderd worden. Dit levert ruis op en miscommunicatie.
